name: "Build and Deploy"
on:
  push:
jobs:
  job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./website"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
